name: rust-toolchain
inputs:
  toolchain:
    description: "Which rust toolchain to use"
    required: false

runs:
  using: "composite"
  steps:
    - id: get-toolchain
      shell: bash
      run: |
        USER_OVERRIDE=${{ inputs.toolchain }}
        DEFAULT_TOOLCHAIN=$(grep channel rust-toolchain.toml | awk '{print $3}' | sed 's/"//g')
        TOOLCHAIN=${USER_OVERRIDE:-$DEFAULT_TOOLCHAIN}
        echo "toolchain=$TOOLCHAIN" >> $GITHUB_OUTPUT
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ steps.get-toolchain.outputs.toolchain }}
        override: true
    - uses: Swatinem/rust-cache@v2.0.0
      with:
        shared-key: "svm-test"
