name: ci-rust-push

on:
  push:
    branches:
      - main

jobs:
  skip-duplicates:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"

  check:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/actions/rust-toolchain
      - run: cargo check --all-features

  test:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/actions/rust-toolchain
      - uses: ./.github/workflows/actions/solana-toolchain
      - run: ./scripts/build_sbf.sh
      - run: cargo test --all-features

  fmt:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/actions/rust-toolchain
        with:
          toolchain: nightly
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  clippy:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/actions/rust-toolchain
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- --deny warnings

  doc:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/workflows/actions/rust-toolchain
      - run: cargo doc --all-features --no-deps
